	Core u0 (
		.audio_and_video_config_external_interface_SDAT  (<connected-to-audio_and_video_config_external_interface_SDAT>),  // audio_and_video_config_external_interface.SDAT
		.audio_and_video_config_external_interface_SCLK  (<connected-to-audio_and_video_config_external_interface_SCLK>),  //                                          .SCLK
		.audio_external_interface_ADCDAT                 (<connected-to-audio_external_interface_ADCDAT>),                 //                  audio_external_interface.ADCDAT
		.audio_external_interface_ADCLRCK                (<connected-to-audio_external_interface_ADCLRCK>),                //                                          .ADCLRCK
		.audio_external_interface_BCLK                   (<connected-to-audio_external_interface_BCLK>),                   //                                          .BCLK
		.audio_external_interface_DACDAT                 (<connected-to-audio_external_interface_DACDAT>),                 //                                          .DACDAT
		.audio_external_interface_DACLRCK                (<connected-to-audio_external_interface_DACLRCK>),                //                                          .DACLRCK
		.clk_clk                                         (<connected-to-clk_clk>),                                         //                                       clk.clk
		.clock_bridge_out_clk_clk                        (<connected-to-clock_bridge_out_clk_clk>),                        //                      clock_bridge_out_clk.clk
		.reset_reset_n                                   (<connected-to-reset_reset_n>),                                   //                                     reset.reset_n
		.sdram_controller_wire_addr                      (<connected-to-sdram_controller_wire_addr>),                      //                     sdram_controller_wire.addr
		.sdram_controller_wire_ba                        (<connected-to-sdram_controller_wire_ba>),                        //                                          .ba
		.sdram_controller_wire_cas_n                     (<connected-to-sdram_controller_wire_cas_n>),                     //                                          .cas_n
		.sdram_controller_wire_cke                       (<connected-to-sdram_controller_wire_cke>),                       //                                          .cke
		.sdram_controller_wire_cs_n                      (<connected-to-sdram_controller_wire_cs_n>),                      //                                          .cs_n
		.sdram_controller_wire_dq                        (<connected-to-sdram_controller_wire_dq>),                        //                                          .dq
		.sdram_controller_wire_dqm                       (<connected-to-sdram_controller_wire_dqm>),                       //                                          .dqm
		.sdram_controller_wire_ras_n                     (<connected-to-sdram_controller_wire_ras_n>),                     //                                          .ras_n
		.sdram_controller_wire_we_n                      (<connected-to-sdram_controller_wire_we_n>),                      //                                          .we_n
		.sram_external_interface_DQ                      (<connected-to-sram_external_interface_DQ>),                      //                   sram_external_interface.DQ
		.sram_external_interface_ADDR                    (<connected-to-sram_external_interface_ADDR>),                    //                                          .ADDR
		.sram_external_interface_LB_N                    (<connected-to-sram_external_interface_LB_N>),                    //                                          .LB_N
		.sram_external_interface_UB_N                    (<connected-to-sram_external_interface_UB_N>),                    //                                          .UB_N
		.sram_external_interface_CE_N                    (<connected-to-sram_external_interface_CE_N>),                    //                                          .CE_N
		.sram_external_interface_OE_N                    (<connected-to-sram_external_interface_OE_N>),                    //                                          .OE_N
		.sram_external_interface_WE_N                    (<connected-to-sram_external_interface_WE_N>),                    //                                          .WE_N
		.sys_sdram_pll_sdram_clk_clk                     (<connected-to-sys_sdram_pll_sdram_clk_clk>),                     //                   sys_sdram_pll_sdram_clk.clk
		.video_vga_controller_external_interface_CLK     (<connected-to-video_vga_controller_external_interface_CLK>),     //   video_vga_controller_external_interface.CLK
		.video_vga_controller_external_interface_HS      (<connected-to-video_vga_controller_external_interface_HS>),      //                                          .HS
		.video_vga_controller_external_interface_VS      (<connected-to-video_vga_controller_external_interface_VS>),      //                                          .VS
		.video_vga_controller_external_interface_BLANK   (<connected-to-video_vga_controller_external_interface_BLANK>),   //                                          .BLANK
		.video_vga_controller_external_interface_SYNC    (<connected-to-video_vga_controller_external_interface_SYNC>),    //                                          .SYNC
		.video_vga_controller_external_interface_DATA_EN (<connected-to-video_vga_controller_external_interface_DATA_EN>), //                                          .DATA_EN
		.video_vga_controller_external_interface_R       (<connected-to-video_vga_controller_external_interface_R>),       //                                          .R
		.video_vga_controller_external_interface_G       (<connected-to-video_vga_controller_external_interface_G>),       //                                          .G
		.video_vga_controller_external_interface_B       (<connected-to-video_vga_controller_external_interface_B>)        //                                          .B
	);

